# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://itangqian.github.io
date_format: "ordinal"
title: candy
subtitle: "如果不努力，就会像糖果一样化掉"
description: "如果不努力，就会像糖果一样化掉"
keywords: candy
timezone: Asia/Chongqing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: candy
organization: 
organization_url: 
github_username: itangqian
location: Chongqing, China
email: 

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  # -
  #   href: /wiki/
  #   label: 维基

  # -
  #   href: /links/
  #   label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
paginate_path: "/blog/page:num/"
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-jupyter-notebook
    - jekyll-mentions
#collections:
#    wiki:
#        output: true
#        permalink: /wiki/:path/

#jekyll_admin:
#    hidden_links:
#        - posts
#        - pages
#        - staticfiles
#        - datafiles
#        - configuration

repository: itangqian/itangqian.github.io

# # ---------------- #
# #      Comments    #
# # ---------------- #
# # support provider: disqus, gitment, gitalk
# comments_provider: gitalk
# # !!!重要!!! 请修改下面这些信息为你自己申请的
# # !!!Important!!! Please modify infos below to yours
# # https://disqus.com
# disqus:
#     username: 
# # https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: mzlogin
#     repo: blog-comments
#     oauth:
#         client_id: d2e1cbbd298958076462
#         client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# # https://github.com/gitalk/gitalk#install
# gitalk:
#     owner: mzlogin
#     repo: blog-comments
#     clientID: d2e1cbbd298958076462
#     clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# # 在使用其它评论组件时可点击显示 Disqus
# lazy_load_disqus : false

# # ---------------- #
# #      Search      #
# # ---------------- #
# simple_jekyll_search:
#     # 是否支持全文搜索
#     fulltext: false
#     # 最多显示多少条搜索结果
#     limit: 10

# # ---------------- #
# #    Analytics     #
# # ---------------- #
# google:
#     analytics_id: UA-80669434-1
